### ISSUE TITLE
Feedback for “Carbon ERP Tech Stack”

### ISSUE THREAD

**Issue by TSpeakism** [barbinbrad/carbon#138]
Hey would love to chat on this ERP can you reach out to me with your email???

**Comment by neilk17** [comment]
What's your email? I'll email you

You can also join the discord server: https://discord.gg/h6CzX4Dw

**Comment by barbinbrad** [comment]
Yeah, please join our discord server!

**Comment by TSpeakism** [comment]
Yep. 

***@***.*** ***@***.***> 


Thanks 
Tom
