### ISSUE TITLE
Phone Input Component

### ISSUE THREAD

**Issue by barbinbrad** [barbinbrad/carbon#69]
- we need a phone component for contacts/companies
- the phone input needs to do some normalization/validation
- there are some headless libraries, but this one seems like it would match our design system well: https://github.com/omeralpi/shadcn-phone-input
- the component should live in `/packages/react/src`
- the component should be imported into `/app/components/form/Phone` and replace the existing implementation

**Comment by neilk17** [comment]
Hey Brad, I can work on this.

p.s. I messaged you on Twitter/ X and would love to chat.

**Comment by barbinbrad** [comment]
Closed by #73
